name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Ana branch'e push yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # İşlemci ortamı

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Kodun repodan çekilmesi

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Node.js ortamını ayarlıyoruz
        with:
          node-version: '16'  # Node.js sürümünü belirliyoruz

      - name: Install dependencies
        run: |
          npm install  # Bağımlılıkları yükle

      - name: Build the project
        run: |
          npm run build  # Build işlemi

      - name: Deploy to Vercel
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Vercel deploy komutu
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Vercel token'ı GitHub Secrets'tan alınacak
